# Generated by Django 4.1.7 on 2023-03-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ByDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, unique=True)),
                ('student_object', models.JSONField()),
            ],
            options={
                'db_table': 'daily',
            },
        ),
    ]
