# Generated by Django 4.1.7 on 2023-03-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_byday'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastudents',
            name='weekday',
            field=models.CharField(default='Monday', max_length=30),
        ),
    ]
