# Generated by Django 4.1.7 on 2023-03-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_datastudents_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='byday',
            name='weekday',
            field=models.CharField(default='Monday', max_length=300),
        ),
    ]
