# Generated by Django 4.1.7 on 2023-03-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_byday_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='byday',
            name='weekday',
            field=models.CharField(default='none', max_length=300),
        ),
    ]
