# Generated by Django 4.1.7 on 2023-03-06 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_alter_byday_weekday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ByDay',
        ),
    ]
