# Generated by Django 4.1.7 on 2023-03-06 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_delete_byday'),
    ]

    operations = [
        migrations.CreateModel(
            name='ByDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, unique=True)),
                ('student_object', models.JSONField()),
                ('weekday', models.CharField(default='none', max_length=20)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.sinf')),
            ],
            options={
                'db_table': 'daily',
            },
        ),
    ]
