# Generated by Django 4.1.7 on 2023-03-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_byday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='byday',
            name='created_at',
            field=models.DateField(auto_created=True),
        ),
    ]
