# Generated by Django 4.1.7 on 2023-03-06 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0010_alter_byday_class_group_alter_byday_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='byday',
            name='datastudent',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='basic_app.datastudents'),
        ),
    ]
