# Generated by Django 4.1.7 on 2023-03-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0011_byday_datastudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='byday',
            name='datastudent',
        ),
    ]
